services:



  db:
      image: postgres:14.5
      restart: always
      volumes:
        - ./data/db:/var/lib/postgresql/data
      environment:
        - POSTGRES_DB=shen
        - POSTGRES_USER=shen
        - POSTGRES_PASSWORD=shenlee
  cache:
    image: redis:7.0.4
    restart: always
    volumes:
    - ./data/cache:/data

  web:
    build: .
    command: ["./wait-for-it.sh", "db:5432", "--",
              "uwsgi", "--ini", "/code/config/uwsgi/uwsgi.ini"]
    restart: always
    volumes:
      - .:/code
    environment:
      - DJANGO_SETTINGS_MODULE=myshop.settings.prod
      - POSTGRES_DB=shen
      - POSTGRES_USER=shen
      - POSTGRES_PASSWORD=shenlee
    depends_on:
      - db
      - cache
  nginx:
    image: nginx:1.23.1
    restart: always
    volumes:
      - ./config/nginx:/etc/nginx/templates
      - .:/code
    ports:
      - "80:80"
      - "443:443"
