services:



  db:
      image: postgres:14.5
      restart: always
      volumes:
        - ./data/db:/var/lib/postgresql/data
      environment:
        - POSTGRES_DB=shen
        - POSTGRES_USER=shen
        - POSTGRES_PASSWORD=shenlee

  web:
    build: .
    command: ["./wait-for-it.sh", "db:5432", "--",
              "python", "/code/manage.py", "runserver", "0.0.0.0:8000"]
    restart: always
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=myshop.settings.prod
      - POSTGRES_DB=shen
      - POSTGRES_USER=shen
      - POSTGRES_PASSWORD=shenlee
    depends_on:
      - db