# Generated by Django 5.1.7 on 2025-04-07 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='coupons',
            new_name='Coupon',
        ),
    ]
