# Generated by Django 5.1.7 on 2025-04-16 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_head'),
    ]

    operations = [
        migrations.AlterField(
            model_name='head',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product/%Y/%m/%d'),
        ),
    ]
