# Generated by Django 5.1.7 on 2025-04-16 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_head_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Head',
        ),
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
