# Generated by Django 5.1.7 on 2025-04-19 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_category_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_featured',
            new_name='featured',
        ),
    ]
