# Generated by Django 5.1.7 on 2025-04-19 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_remove_product_featured_category_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='Countdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Sale Ends In', max_length=100)),
                ('end_date', models.DateTimeField()),
            ],
        ),
    ]
