# Generated by Django 5.1.7 on 2025-04-25 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_nftcard'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NFTCard',
        ),
    ]
