# Generated by Django 5.1.7 on 2025-04-25 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_delete_nftcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='artworks/images/')),
                ('pdf', models.FileField(upload_to='artworks/pdfs/')),
            ],
        ),
    ]
