# Generated by Django 5.1.7 on 2025-04-25 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_artwork'),
    ]

    operations = [
        migrations.CreateModel(
            name='NFTCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('artist_name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='nft/images/')),
                ('pdf', models.FileField(upload_to='nft/pdfs/')),
            ],
        ),
        migrations.DeleteModel(
            name='Artwork',
        ),
    ]
