# Generated by Django 5.1.7 on 2025-03-24 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('shop', '0002_rename_category_product_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='order_item',
            new_name='OrderItem',
        ),
    ]
