# Generated by Django 5.1.7 on 2025-04-22 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_mpesa_receipt_order_payment_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='mpesa_receipt',
            new_name='mpesa_code',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_status',
        ),
    ]
