# Generated by Django 5.1.7 on 2025-04-22 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_rename_mpesa_receipt_order_mpesa_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid_via',
            field=models.CharField(blank=True, choices=[('stripe', 'Stripe'), ('mpesa', 'M-Pesa')], max_length=20, null=True),
        ),
    ]
