# Generated by Django 5.1.7 on 2025-04-22 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_paid_via'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='download_link_sent',
            field=models.BooleanField(default=False),
        ),
    ]
