# Generated by Django 4.1.13 on 2025-05-24 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order_shipping_tracking_number_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paid_via',
            field=models.CharField(blank=True, choices=[('stripe', 'Stripe'), ('mpesa', 'M-Pesa'), ('cod', 'Cash on Delivery')], max_length=20, null=True),
        ),
    ]
